export const DISCIPLINE_CATEGORIES = [
  {
    id: "levantamento",
    name: "Levantamento",
    icon: "Map",
    color: "blue",
    subcategories: [
      { id: "topografico", name: "Projeto Topográfico" },
      { id: "sondagem", name: "Sondagem do Solo" },
    ],
  },
  {
    id: "arquitetonico",
    name: "Projeto Arquitetônico",
    icon: "Building",
    color: "purple",
    subcategories: [
      { id: "preliminar", name: "Projeto Preliminar" },
      { id: "legal", name: "Projeto Legal" },
      { id: "executivo", name: "Projeto Executivo" },
      { id: "condominio", name: "Projeto Condomínio" },
    ],
  },
  {
    id: "implantacao",
    name: "Projeto de Implantação",
    icon: "MapPin",
    color: "green",
    subcategories: [
      { id: "geral", name: "Implantação Geral" },
    ],
  },
  {
    id: "estrutural",
    name: "Projeto Estrutural",
    icon: "Columns",
    color: "slate",
    subcategories: [
      { id: "fundacao", name: "Fundação e Superestrutura" },
      { id: "muro", name: "Muro de Arrimo" },
      { id: "metalica", name: "Estrutura Metálica" },
    ],
  },
  {
    id: "hidrossanitario",
    name: "Projeto Hidrossanitário",
    icon: "Droplet",
    color: "cyan",
    subcategories: [
      { id: "hidraulico", name: "Hidráulico" },
      { id: "sanitario", name: "Sanitário" },
      { id: "pluvial", name: "Pluvial" },
    ],
  },
  {
    id: "eletrico",
    name: "Projeto Elétrico",
    icon: "Zap",
    color: "yellow",
    subcategories: [
      { id: "pontos", name: "Pontos Elétricos" },
      { id: "luminotecnico", name: "Luminotécnico" },
      { id: "automacao", name: "Automação" },
      { id: "cabeamento", name: "Cabeamento Estruturado / Comunicação" },
    ],
  },
  {
    id: "climatizacao",
    name: "Projeto Climatização",
    icon: "Wind",
    color: "sky",
    subcategories: [
      { id: "locacao_aparelhos", name: "Locação Aparelhos" },
      { id: "pontos_eletricos", name: "Pontos Elétricos" },
      { id: "drenagem", name: "Drenagem" },
    ],
  },
  {
    id: "incendio",
    name: "Projeto Incêndio",
    icon: "Flame",
    color: "red",
    subcategories: [
      { id: "ppci", name: "PPCI" },
      { id: "spda", name: "SPDA" },
    ],
  },
  {
    id: "vigilancia",
    name: "Projeto Vigilância Sanitária",
    icon: "ShieldCheck",
    color: "emerald",
    subcategories: [
      { id: "geral", name: "Vigilância Sanitária" },
    ],
  },
  {
    id: "gas",
    name: "Projeto de Gás",
    icon: "Flame",
    color: "orange",
    subcategories: [
      { id: "geral", name: "Instalação de Gás" },
    ],
  },
  {
    id: "piscina",
    name: "Projeto Piscina",
    icon: "Waves",
    color: "blue",
    subcategories: [
      { id: "estrutural", name: "Estrutural" },
      { id: "luminotecnico", name: "Luminotécnico" },
      { id: "hidromassagem", name: "Hidromassagem" },
      { id: "cobertura", name: "Capa / Cobertura Retrátil" },
    ],
  },
  {
    id: "paisagismo",
    name: "Projeto Paisagismo",
    icon: "Trees",
    color: "green",
    subcategories: [
      { id: "locacao_plantas", name: "Locação das Plantas" },
      { id: "pedido_plantas", name: "Pedido das Plantas" },
      { id: "luminotecnico", name: "Luminotécnico" },
      { id: "irrigacao", name: "Irrigação" },
    ],
  },
  {
    id: "interiores",
    name: "Projeto de Interiores",
    icon: "Home",
    color: "pink",
    subcategories: [
      { id: "hidraulico", name: "Hidráulico" },
      { id: "sanitario", name: "Sanitário" },
      { id: "layout", name: "Layout do Mobiliário" },
      { id: "renders", name: "Imagens Renderizadas" },
      { id: "luminotecnico", name: "Luminotécnico" },
      { id: "tomadas", name: "Tomadas e Interruptores" },
      { id: "pontos_hidraulicos", name: "Pontos Hidráulicos" },
      { id: "forro", name: "Detalhamento Forro" },
      { id: "revestimentos", name: "Detalhamento Revestimentos" },
      { id: "marmoraria", name: "Detalhamento Marmoraria" },
      { id: "marcenaria", name: "Detalhamento Marcenaria" },
      { id: "bases", name: "Projeto de Bases" },
    ],
  },
  {
    id: "listas",
    name: "Listas Técnicas",
    icon: "ClipboardList",
    color: "violet",
    subcategories: [
      { id: "esquadrias", name: "Esquadrias e Portas Internas" },
      { id: "ar_condicionado", name: "Aparelhos de Ar-Condicionado" },
      { id: "revestimentos", name: "Revestimentos" },
      { id: "loucas_metais", name: "Louças e Metais" },
      { id: "luminarias", name: "Luminárias" },
      { id: "tomadas_interruptores", name: "Tomadas e Interruptores" },
      { id: "eletrodomesticos", name: "Eletrodomésticos" },
      { id: "pintura", name: "Pintura" },
      { id: "cortinas", name: "Cortinas" },
      { id: "papel_parede", name: "Papel de Parede" },
      { id: "box_espelhos", name: "Box e Espelhos" },
    ],
  },
];

export const TASK_TEMPLATES: Record<string, Array<{ title: string; description: string }>> = {
  // LEVANTAMENTO
  topografico: [
    { title: "Solicitar orçamentos de topografia", description: "Pesquisar e solicitar no mínimo 3 orçamentos de empresas especializadas" },
    { title: "Contratar empresa de topografia", description: "Analisar propostas e contratar empresa com melhor custo-benefício" },
    { title: "Agendar visita ao terreno", description: "Coordenar data e horário com topógrafo e proprietário" },
    { title: "Realizar levantamento topográfico", description: "Acompanhar execução das medições em campo" },
    { title: "Receber e conferir planta topográfica", description: "Verificar amarração, curvas de nível e pontos de referência" },
    { title: "Aprovar levantamento topográfico", description: "Validar dados e autorizar uso no projeto" },
  ],
  sondagem: [
    { title: "Solicitar orçamentos de sondagem", description: "Contatar empresas especializadas em sondagem SPT" },
    { title: "Definir quantidade de furos", description: "Calcular quantidade necessária conforme NBR 8036" },
    { title: "Contratar empresa de sondagem", description: "Fechar contrato com empresa selecionada" },
    { title: "Marcar data para sondagem", description: "Agendar execução dos furos com proprietário" },
    { title: "Acompanhar execução da sondagem", description: "Verificar profundidade e procedimentos em campo" },
    { title: "Receber laudo de sondagem", description: "Obter relatório técnico com resistência do solo" },
    { title: "Analisar capacidade de carga", description: "Avaliar dados para definição do tipo de fundação" },
    { title: "Enviar laudo para estrutural", description: "Encaminhar relatório ao projetista estrutural" },
  ],

  // ARQUITETÔNICO
  preliminar: [
    { title: "Reunião inicial com cliente", description: "Levantar necessidades, desejos e orçamento disponível" },
    { title: "Analisar legislação local", description: "Verificar código de obras, zoneamento e restrições" },
    { title: "Fazer estudo de viabilidade", description: "Calcular área máxima permitida e ocupação do terreno" },
    { title: "Desenvolver croquis iniciais", description: "Criar primeiras opções de implantação e distribuição" },
    { title: "Elaborar planta baixa preliminar", description: "Definir ambientes, dimensões e fluxos" },
    { title: "Criar estudo volumétrico", description: "Desenvolver maquete eletrônica ou croquis 3D" },
    { title: "Apresentar estudo ao cliente", description: "Reunir para apresentação e coleta de feedback" },
    { title: "Revisar projeto conforme retorno", description: "Implementar ajustes solicitados pelo cliente" },
    { title: "Obter aprovação do estudo", description: "Confirmar aprovação para seguir com projeto legal" },
  ],
  legal: [
    { title: "Verificar documentação do terreno", description: "Conferir matrícula, RGI e certidões negativas" },
    { title: "Consultar código de obras municipal", description: "Verificar parâmetros urbanísticos aplicáveis" },
    { title: "Adequar projeto aos parâmetros", description: "Ajustar recuos, taxa de ocupação e gabarito" },
    { title: "Elaborar plantas para aprovação", description: "Criar pranchas conforme exigências da prefeitura" },
    { title: "Preparar memorial descritivo", description: "Redigir memorial técnico do projeto" },
    { title: "Organizar documentação necessária", description: "Reunir ART, procurações e documentos do proprietário" },
    { title: "Protocolar na prefeitura", description: "Dar entrada no processo de aprovação" },
    { title: "Acompanhar análise do projeto", description: "Verificar andamento e responder pendências" },
    { title: "Resolver pendências da análise", description: "Atender exigências e complementar documentação" },
    { title: "Receber alvará de construção", description: "Obter documento liberando início da obra" },
  ],
  executivo: [
    { title: "Detalhar plantas de cada pavimento", description: "Criar plantas com todas as informações para execução" },
    { title: "Elaborar cortes transversais", description: "Desenvolver cortes mostrando pé-direito e níveis" },
    { title: "Desenvolver fachadas", description: "Detalhar todas as elevações do projeto" },
    { title: "Detalhar escadas e rampas", description: "Criar plantas e cortes de acessos verticais" },
    { title: "Especificar revestimentos", description: "Definir materiais de pisos, paredes e tetos" },
    { title: "Criar planta de paginação", description: "Detalhar paginação de pisos e revestimentos" },
    { title: "Elaborar detalhes construtivos", description: "Desenhar encontros, arremates e soluções especiais" },
    { title: "Detalhar esquadrias", description: "Criar plantas de esquadrias com especificações" },
    { title: "Compatibilizar com complementares", description: "Verificar interferências com estrutura e instalações" },
    { title: "Revisar conjunto de pranchas", description: "Verificar consistência entre desenhos" },
    { title: "Preparar caderno de especificações", description: "Elaborar memorial descritivo dos acabamentos" },
  ],
  condominio: [
    { title: "Verificar convenção do condomínio", description: "Analisar restrições e exigências condominiais" },
    { title: "Contatar síndico ou administradora", description: "Obter orientações sobre processo de aprovação" },
    { title: "Preparar documentação necessária", description: "Reunir plantas, memoriais e documentos exigidos" },
    { title: "Elaborar memorial de acabamentos", description: "Descrever materiais externos conforme padrão" },
    { title: "Protocolar no condomínio", description: "Submeter projeto para análise condominial" },
    { title: "Participar de reunião da comissão", description: "Apresentar projeto se necessário" },
    { title: "Atender pendências levantadas", description: "Ajustar projeto conforme exigências" },
    { title: "Obter aprovação do condomínio", description: "Receber autorização para execução da obra" },
  ],

  // IMPLANTAÇÃO
  implantacao_geral: [
    { title: "Marcar pontos de referência", description: "Definir marcos para locação da obra" },
    { title: "Elaborar planta de implantação", description: "Posicionar edificação no terreno" },
    { title: "Definir cotas de nível", description: "Estabelecer níveis de piso e terraplanagem" },
    { title: "Planejar terraplanagem", description: "Calcular volumes de corte e aterro" },
    { title: "Definir acessos provisórios", description: "Planejar entrada de veículos e equipamentos" },
    { title: "Locar canteiro de obras", description: "Posicionar áreas de vivência e estoque" },
    { title: "Marcar alinhamento predial", description: "Demarcar recuos e divisas" },
  ],

  // ESTRUTURAL
  fundacao: [
    { title: "Analisar laudo de sondagem", description: "Estudar capacidade de carga do solo" },
    { title: "Definir tipo de fundação", description: "Escolher entre sapatas, estacas ou radier" },
    { title: "Calcular cargas da estrutura", description: "Quantificar cargas permanentes e acidentais" },
    { title: "Dimensionar elementos de fundação", description: "Calcular dimensões de sapatas ou estacas" },
    { title: "Elaborar planta de formas", description: "Desenhar disposição dos elementos" },
    { title: "Detalhar armações de fundação", description: "Especificar bitolas e espaçamentos" },
    { title: "Calcular pilares e vigas", description: "Dimensionar elementos da superestrutura" },
    { title: "Dimensionar lajes", description: "Calcular espessuras e armações de lajes" },
    { title: "Criar memorial de cálculo", description: "Documentar premissas e resultados" },
    { title: "Emitir ART do projeto estrutural", description: "Registrar responsabilidade técnica" },
  ],
  muro: [
    { title: "Avaliar altura e empuxo", description: "Calcular esforços do solo a conter" },
    { title: "Definir tipo de contenção", description: "Escolher entre muro de arrimo, gabiões ou cortina" },
    { title: "Dimensionar estrutura do muro", description: "Calcular espessuras e armações" },
    { title: "Projetar sistema de drenagem", description: "Definir drenos e barbacãs" },
    { title: "Detalhar fundação do muro", description: "Dimensionar base e sapata corrida" },
    { title: "Especificar impermeabilização", description: "Definir proteção contra umidade" },
    { title: "Elaborar memorial descritivo", description: "Documentar características técnicas" },
  ],
  metalica: [
    { title: "Definir sistema estrutural", description: "Escolher tipo de ligações e perfis" },
    { title: "Dimensionar perfis metálicos", description: "Calcular vigas, pilares e treliças" },
    { title: "Detalhar ligações", description: "Especificar soldas e parafusos" },
    { title: "Elaborar lista de materiais", description: "Quantificar perfis e acessórios" },
    { title: "Especificar pintura e proteção", description: "Definir tratamento anticorrosivo" },
    { title: "Criar desenhos de fabricação", description: "Detalhar peças para oficina" },
    { title: "Planejar sequência de montagem", description: "Definir ordem de instalação" },
  ],

  // HIDROSSANITÁRIO
  hidraulico: [
    { title: "Calcular consumo de água", description: "Estimar demanda diária e vazões" },
    { title: "Dimensionar reservatórios", description: "Calcular volumes de cisternas e caixas d'água" },
    { title: "Projetar entrada de água", description: "Definir ramal predial e cavalete" },
    { title: "Dimensionar tubulações", description: "Calcular diâmetros de prumadas e ramais" },
    { title: "Definir sistema de recalque", description: "Especificar bombas se necessário" },
    { title: "Elaborar isométricos", description: "Criar desenhos 3D das instalações" },
    { title: "Especificar materiais", description: "Definir tipos de tubos e conexões" },
    { title: "Calcular sistema de água quente", description: "Dimensionar aquecimento e distribuição" },
  ],
  sanitario: [
    { title: "Dimensionar rede de esgoto", description: "Calcular diâmetros conforme NBR 8160" },
    { title: "Definir caixas de inspeção", description: "Posicionar caixas de passagem" },
    { title: "Projetar sistema de ventilação", description: "Dimensionar tubos de ventilação" },
    { title: "Detalhar fossa séptica", description: "Calcular volume se não houver rede pública" },
    { title: "Projetar sumidouro ou filtro", description: "Dimensionar sistema de infiltração" },
    { title: "Elaborar planta de esgoto", description: "Desenhar prumadas e ramais" },
    { title: "Especificar materiais", description: "Definir tubos, conexões e caixas" },
    { title: "Criar memorial de cálculo", description: "Documentar dimensionamentos" },
  ],
  pluvial: [
    { title: "Calcular área de contribuição", description: "Medir superfícies de captação" },
    { title: "Dimensionar calhas e condutores", description: "Calcular seções conforme chuva local" },
    { title: "Definir pontos de descida", description: "Posicionar condutores verticais" },
    { title: "Projetar caixas de areia", description: "Posicionar caixas de inspeção" },
    { title: "Dimensionar drenagem do terreno", description: "Calcular sarjetas e grelhas" },
    { title: "Verificar destino final", description: "Confirmar galeria pública ou infiltração" },
    { title: "Elaborar planta de drenagem", description: "Desenhar sistema completo" },
  ],

  // ELÉTRICO
  pontos: [
    { title: "Levantar cargas elétricas", description: "Listar todos os equipamentos e potências" },
    { title: "Calcular demanda total", description: "Somar cargas com fatores de diversidade" },
    { title: "Dimensionar entrada de energia", description: "Definir padrão junto à concessionária" },
    { title: "Dividir circuitos elétricos", description: "Separar por tipo e ambiente" },
    { title: "Dimensionar condutores", description: "Calcular bitolas conforme corrente" },
    { title: "Dimensionar proteções", description: "Especificar disjuntores e DRs" },
    { title: "Elaborar diagrama unifilar", description: "Desenhar esquema dos quadros" },
    { title: "Criar planta de pontos", description: "Locar tomadas, interruptores e luminárias" },
    { title: "Especificar quadros elétricos", description: "Definir características dos painéis" },
    { title: "Preparar memorial descritivo", description: "Documentar especificações técnicas" },
  ],
  luminotecnico: [
    { title: "Definir conceito de iluminação", description: "Estabelecer atmosfera e níveis desejados" },
    { title: "Calcular iluminância necessária", description: "Verificar níveis conforme NBR 8995" },
    { title: "Selecionar tipos de luminárias", description: "Escolher modelos adequados a cada ambiente" },
    { title: "Fazer cálculo luminotécnico", description: "Simular distribuição de luz" },
    { title: "Definir temperatura de cor", description: "Especificar tons de luz (K)" },
    { title: "Especificar dimerizações", description: "Definir controles de intensidade" },
    { title: "Elaborar planta de pontos de luz", description: "Locar todas as luminárias" },
    { title: "Criar tabela de luminárias", description: "Listar modelos e quantidades" },
  ],
  automacao: [
    { title: "Levantar necessidades de automação", description: "Definir sistemas a automatizar" },
    { title: "Escolher plataforma de controle", description: "Selecionar tecnologia (KNX, Zigbee, etc)" },
    { title: "Projetar rede de automação", description: "Definir cabeamento e topologia" },
    { title: "Especificar dispositivos", description: "Escolher sensores, atuadores e controladores" },
    { title: "Planejar cenários de uso", description: "Programar rotinas e automações" },
    { title: "Elaborar diagrama de lógica", description: "Documentar programação" },
    { title: "Integrar com outros sistemas", description: "Compatibilizar com iluminação, HVAC, etc" },
  ],
  cabeamento: [
    { title: "Definir requisitos de rede", description: "Estabelecer velocidades e quantidade de pontos" },
    { title: "Projetar topologia de rede", description: "Definir distribuição e rack" },
    { title: "Dimensionar cabeamento estruturado", description: "Calcular metragens de cabos" },
    { title: "Especificar categoria de cabos", description: "Definir Cat6, Cat6A ou fibra" },
    { title: "Locar pontos de rede", description: "Posicionar tomadas RJ45" },
    { title: "Projetar sistema de som", description: "Definir alto-falantes e cabeamento" },
    { title: "Especificar rack e patch panel", description: "Definir equipamentos do centro de distribuição" },
    { title: "Elaborar diagrama lógico", description: "Desenhar esquema de conexões" },
  ],

  // CLIMATIZAÇÃO
  locacao_aparelhos: [
    { title: "Calcular carga térmica", description: "Estimar BTUs necessários por ambiente" },
    { title: "Selecionar modelos de equipamentos", description: "Escolher splits ou VRF" },
    { title: "Definir posição das evaporadoras", description: "Locar unidades internas otimizando distribuição" },
    { title: "Definir posição das condensadoras", description: "Posicionar unidades externas" },
    { title: "Verificar distâncias permitidas", description: "Confirmar comprimentos de tubulação" },
    { title: "Elaborar planta de locação", description: "Desenhar posicionamento dos equipamentos" },
  ],
  pontos_eletricos: [
    { title: "Levantar potências dos equipamentos", description: "Verificar consumo de cada aparelho" },
    { title: "Dimensionar circuitos exclusivos", description: "Calcular circuitos para cada condensadora" },
    { title: "Locar pontos elétricos", description: "Posicionar tomadas para as unidades" },
    { title: "Especificar proteções elétricas", description: "Definir disjuntores adequados" },
    { title: "Elaborar diagrama elétrico", description: "Desenhar esquema de alimentação" },
  ],
  drenagem: [
    { title: "Definir pontos de dreno", description: "Posicionar saídas de condensado" },
    { title: "Dimensionar tubulação de dreno", description: "Calcular diâmetros necessários" },
    { title: "Planejar caminho até esgoto", description: "Definir trajeto das tubulações" },
    { title: "Especificar sifões", description: "Definir proteção contra refluxo de odor" },
    { title: "Elaborar planta de drenagem", description: "Desenhar sistema de condensado" },
  ],

  // INCÊNDIO
  ppci: [
    { title: "Classificar uso e ocupação", description: "Definir categoria conforme IT-CBMSP" },
    { title: "Dimensionar extintores", description: "Calcular quantidade e tipos" },
    { title: "Projetar hidrantes", description: "Definir posições e reserva técnica" },
    { title: "Dimensionar sprinklers", description: "Calcular rede de chuveiros automáticos se aplicável" },
    { title: "Projetar iluminação de emergência", description: "Locar blocos autônomos" },
    { title: "Definir sinalização de emergência", description: "Posicionar placas fotoluminescentes" },
    { title: "Elaborar rotas de fuga", description: "Desenhar saídas de emergência" },
    { title: "Preparar memorial PPCI", description: "Documentar sistema de segurança" },
    { title: "Protocolar no Corpo de Bombeiros", description: "Submeter projeto para aprovação" },
  ],
  spda: [
    { title: "Avaliar nível de proteção necessário", description: "Definir NPR conforme NBR 5419" },
    { title: "Projetar captores", description: "Dimensionar hastes Franklin ou gaiola" },
    { title: "Dimensionar descidas", description: "Calcular quantidade de condutores" },
    { title: "Projetar aterramento", description: "Definir malha de terra" },
    { title: "Especificar materiais", description: "Definir cabos, conectores e hastes" },
    { title: "Elaborar planta de SPDA", description: "Desenhar sistema completo" },
    { title: "Emitir laudo de para-raios", description: "Documentar conformidade" },
  ],

  // VIGILÂNCIA SANITÁRIA
  vigilancia_geral: [
    { title: "Verificar atividades sujeitas à vigilância", description: "Confirmar necessidade de aprovação" },
    { title: "Consultar legislação aplicável", description: "Verificar RDC e portarias municipais" },
    { title: "Adequar projeto aos requisitos", description: "Ajustar ambientes conforme normas" },
    { title: "Preparar memorial técnico", description: "Descrever processos e fluxos" },
    { title: "Organizar documentação", description: "Reunir plantas, ARTs e licenças" },
    { title: "Protocolar na Vigilância Sanitária", description: "Dar entrada no processo" },
    { title: "Atender pendências levantadas", description: "Complementar documentação se solicitado" },
    { title: "Obter alvará sanitário", description: "Receber licença de funcionamento" },
  ],

  // GÁS
  gas_geral: [
    { title: "Dimensionar consumo de gás", description: "Calcular vazão necessária (m³/h)" },
    { title: "Definir tipo de gás", description: "Especificar GLP ou GN" },
    { title: "Projetar rede de distribuição", description: "Dimensionar tubulações" },
    { title: "Definir abrigo de gás", description: "Projetar casa de gás conforme normas" },
    { title: "Especificar reguladores", description: "Definir pressões de trabalho" },
    { title: "Locar pontos de utilização", description: "Posicionar registros e conexões" },
    { title: "Elaborar planta de gás", description: "Desenhar instalação completa" },
    { title: "Preparar memorial descritivo", description: "Documentar especificações" },
    { title: "Obter aprovação da concessionária", description: "Submeter projeto se necessário" },
  ],

  // PISCINA
  piscina_estrutural: [
    { title: "Definir tipo de piscina", description: "Escolher entre concreto, vinil ou fibra" },
    { title: "Calcular empuxo hidrostático", description: "Dimensionar esforços da água" },
    { title: "Dimensionar estrutura de contenção", description: "Calcular espessuras e armações" },
    { title: "Projetar laje de fundo", description: "Dimensionar base da piscina" },
    { title: "Detalhar bordas e degraus", description: "Especificar acabamentos" },
    { title: "Elaborar cortes detalhados", description: "Mostrar todas as camadas" },
    { title: "Especificar impermeabilização", description: "Definir sistema de vedação" },
  ],
  piscina_luminotecnico: [
    { title: "Definir tipo de iluminação", description: "Escolher LED submerso ou periférico" },
    { title: "Calcular quantidade de refletores", description: "Dimensionar conforme área" },
    { title: "Especificar potência e cor", description: "Definir watts e temperatura" },
    { title: "Locar pontos de luz", description: "Posicionar refletores na piscina" },
    { title: "Dimensionar circuito elétrico", description: "Calcular proteções e condutores" },
    { title: "Especificar transformador", description: "Definir redução para 12V" },
  ],
  hidromassagem: [
    { title: "Definir tipo de hidromassagem", description: "Escolher jatos ou soprador" },
    { title: "Dimensionar bomba de hidro", description: "Calcular vazão necessária" },
    { title: "Locar bocais de hidromassagem", description: "Posicionar jatos ergonomicamente" },
    { title: "Projetar tubulação de retorno", description: "Dimensionar rede de distribuição" },
    { title: "Especificar equipamentos", description: "Definir marcas e modelos" },
    { title: "Elaborar diagrama hidráulico", description: "Desenhar sistema completo" },
  ],
  cobertura: [
    { title: "Definir tipo de cobertura", description: "Escolher entre manual ou automática" },
    { title: "Dimensionar estrutura de suporte", description: "Calcular vigas e trilhos" },
    { title: "Especificar material da lona", description: "Definir tipo de proteção" },
    { title: "Projetar sistema de acionamento", description: "Especificar motor se automático" },
    { title: "Detalhar fixações", description: "Definir ancoragens e guias" },
    { title: "Elaborar memorial técnico", description: "Documentar sistema" },
  ],

  // PAISAGISMO
  paisagismo_locacao_plantas: [
    { title: "Fazer levantamento do solo", description: "Analisar pH, drenagem e insolação" },
    { title: "Definir paleta vegetal", description: "Selecionar espécies adequadas ao clima" },
    { title: "Elaborar planta de massas", description: "Distribuir árvores, arbustos e forrações" },
    { title: "Especificar tamanhos de plantio", description: "Definir altura e diâmetro de copa" },
    { title: "Preparar lista de plantas", description: "Quantificar por espécie" },
    { title: "Detalhar canteiros e jardineiras", description: "Especificar dimensões e acabamentos" },
  ],
  paisagismo_pedido_plantas: [
    { title: "Solicitar orçamentos de viveiros", description: "Pesquisar fornecedores de plantas" },
    { title: "Verificar disponibilidade", description: "Confirmar espécies em estoque" },
    { title: "Fechar pedido de plantas", description: "Encomendar mudas necessárias" },
    { title: "Agendar entrega", description: "Coordenar recebimento na obra" },
    { title: "Conferir qualidade das mudas", description: "Verificar sanidade e tamanho" },
  ],
  paisagismo_luminotecnico: [
    { title: "Definir conceito de iluminação", description: "Estabelecer efeitos desejados" },
    { title: "Selecionar luminárias externas", description: "Escolher modelos para jardim" },
    { title: "Locar pontos de luz", description: "Posicionar espetos e arandelas" },
    { title: "Definir fotocélula", description: "Programar acionamento automático" },
    { title: "Dimensionar circuito externo", description: "Calcular proteção adequada" },
    { title: "Especificar temperatura de cor", description: "Definir tons de luz" },
  ],
  paisagismo_irrigacao: [
    { title: "Calcular necessidade hídrica", description: "Estimar consumo de água das plantas" },
    { title: "Definir sistema de irrigação", description: "Escolher aspersores ou gotejamento" },
    { title: "Dimensionar tubulação", description: "Calcular diâmetros da rede" },
    { title: "Locar aspersores e gotejadores", description: "Posicionar pontos de água" },
    { title: "Especificar controlador", description: "Definir automação e setores" },
    { title: "Elaborar planta de irrigação", description: "Desenhar sistema completo" },
  ],

  // INTERIORES
  interiores_hidraulico: [
    { title: "Definir pontos de água", description: "Locar torneiras e registros" },
    { title: "Especificar metais", description: "Escolher modelos e acabamentos" },
    { title: "Dimensionar aquecimento", description: "Definir sistema de água quente" },
    { title: "Elaborar isométrico", description: "Criar desenho 3D da instalação" },
  ],
  interiores_sanitario: [
    { title: "Definir pontos de esgoto", description: "Locar ralos e saídas de louças" },
    { title: "Especificar louças sanitárias", description: "Escolher modelos e cores" },
    { title: "Projetar ventilação", description: "Dimensionar tubos de ventilação" },
    { title: "Elaborar detalhamento", description: "Criar plantas específicas" },
  ],
  layout: [
    { title: "Fazer levantamento de necessidades", description: "Definir móveis essenciais" },
    { title: "Criar estudo de layout", description: "Distribuir mobiliário otimizando circulação" },
    { title: "Desenvolver plantas humanizadas", description: "Desenhar móveis em planta baixa" },
    { title: "Verificar ergonomia", description: "Conferir alturas e distâncias" },
    { title: "Apresentar opções ao cliente", description: "Mostrar alternativas de distribuição" },
    { title: "Finalizar layout aprovado", description: "Ajustar conforme feedback" },
  ],
  renders: [
    { title: "Modelar ambientes em 3D", description: "Criar geometria dos espaços" },
    { title: "Aplicar materiais e texturas", description: "Definir acabamentos nos modelos" },
    { title: "Configurar iluminação", description: "Posicionar luzes artificiais e naturais" },
    { title: "Renderizar imagens fotorrealistas", description: "Gerar visualizações de alta qualidade" },
    { title: "Pós-processar renderizações", description: "Ajustar cores e saturação" },
    { title: "Apresentar ao cliente", description: "Mostrar ambientações finalizadas" },
  ],
  interiores_luminotecnico: [
    { title: "Definir atmosfera dos ambientes", description: "Estabelecer iluminação geral, focal e decorativa" },
    { title: "Selecionar luminárias", description: "Escolher pendentes, spots e fitas LED" },
    { title: "Calcular iluminância", description: "Verificar níveis de luz adequados" },
    { title: "Locar pontos de luz", description: "Posicionar todas as luminárias" },
    { title: "Especificar dimmers", description: "Definir controles de intensidade" },
    { title: "Criar planta de teto refletido", description: "Desenhar forro com iluminação" },
  ],
  tomadas: [
    { title: "Fazer levantamento de equipamentos", description: "Listar aparelhos elétricos de cada ambiente" },
    { title: "Locar tomadas de uso geral", description: "Posicionar conforme NBR 5410" },
    { title: "Locar tomadas específicas", description: "Definir pontos para eletrodomésticos" },
    { title: "Posicionar interruptores", description: "Locar comandos de iluminação" },
    { title: "Definir alturas de instalação", description: "Especificar cotas de montagem" },
    { title: "Elaborar planta elétrica", description: "Desenhar circuitos e pontos" },
  ],
  pontos_hidraulicos: [
    { title: "Locar pontos de água fria", description: "Posicionar saídas de torneiras" },
    { title: "Locar pontos de água quente", description: "Definir alimentação de chuveiros e torneiras" },
    { title: "Especificar registros", description: "Definir tipos e posições" },
    { title: "Definir alturas de instalação", description: "Cotar pontos hidráulicos" },
    { title: "Elaborar planta hidráulica", description: "Desenhar instalações" },
  ],
  forro: [
    { title: "Definir tipo de forro", description: "Escolher entre gesso, drywall ou modular" },
    { title: "Elaborar desenho do forro", description: "Criar planta de teto" },
    { title: "Detalhar molduras e sancas", description: "Especificar acabamentos" },
    { title: "Definir alturas e desníveis", description: "Cotar pé-direitos" },
    { title: "Integrar iluminação embutida", description: "Recortes para spots e pendentes" },
    { title: "Especificar acabamentos", description: "Definir pintura ou revestimento" },
  ],
  revestimentos: [
    { title: "Selecionar revestimentos de piso", description: "Escolher materiais por ambiente" },
    { title: "Selecionar revestimentos de parede", description: "Definir acabamentos verticais" },
    { title: "Criar planta de paginação", description: "Desenhar layout de assentamento" },
    { title: "Especificar rodapés", description: "Definir acabamento de encontro" },
    { title: "Especificar rejuntes", description: "Escolher cores e tipos" },
    { title: "Elaborar memorial de revestimentos", description: "Documentar todas as especificações" },
  ],
  marmoraria: [
    { title: "Definir aplicações de mármore/granito", description: "Escolher bancadas e soleiras" },
    { title: "Selecionar tipos de pedra", description: "Especificar mármores e granitos" },
    { title: "Dimensionar bancadas", description: "Criar plantas com medidas exatas" },
    { title: "Detalhar bordas e acabamentos", description: "Definir chanfros e arremates" },
    { title: "Especificar cubas e recortes", description: "Posicionar furos e encaixes" },
    { title: "Elaborar projeto executivo", description: "Criar desenhos para marmoraria" },
  ],
  marcenaria: [
    { title: "Definir móveis planejados", description: "Listar armários e móveis fixos" },
    { title: "Dimensionar módulos", description: "Criar medidas de cada peça" },
    { title: "Selecionar materiais", description: "Escolher MDF, MDP ou madeira maciça" },
    { title: "Definir acabamentos", description: "Especificar laminados ou pinturas" },
    { title: "Detalhar ferragens", description: "Escolher puxadores, dobradiças e corrediças" },
    { title: "Criar projeto executivo", description: "Desenhos detalhados para marceneiro" },
    { title: "Elaborar memorial descritivo", description: "Documentar especificações" },
  ],
  bases: [
    { title: "Definir equipamentos a instalar", description: "Listar aparelhos e suas bases" },
    { title: "Dimensionar bases de alvenaria", description: "Calcular tamanhos necessários" },
    { title: "Especificar revestimentos", description: "Definir acabamentos das bases" },
    { title: "Detalhar nichos e prateleiras", description: "Criar desenhos de embutidos" },
    { title: "Elaborar cortes detalhados", description: "Mostrar construção das bases" },
  ],

  // LISTAS
  listas_esquadrias: [
    { title: "Fazer levantamento de vãos", description: "Medir todas as aberturas" },
    { title: "Definir tipos de esquadrias", description: "Escolher entre alumínio, PVC ou madeira" },
    { title: "Especificar modelos", description: "Definir sistemas de abertura" },
    { title: "Selecionar vidros", description: "Especificar espessuras e tipos" },
    { title: "Escolher acabamentos", description: "Definir cores e texturas" },
    { title: "Elaborar lista quantitativa", description: "Criar planilha com todas as esquadrias" },
    { title: "Criar tabela de portas", description: "Listar portas internas com especificações" },
  ],
  listas_ar_condicionado: [
    { title: "Calcular carga térmica", description: "Estimar BTUs por ambiente" },
    { title: "Selecionar modelos", description: "Escolher aparelhos adequados" },
    { title: "Definir eficiência energética", description: "Optar por selo Procel A" },
    { title: "Especificar marca e linha", description: "Definir fabricante" },
    { title: "Elaborar lista de aparelhos", description: "Quantificar por tipo" },
  ],
  listas_revestimentos: [
    { title: "Selecionar pisos", description: "Escolher materiais por ambiente" },
    { title: "Selecionar revestimentos de parede", description: "Definir acabamentos verticais" },
    { title: "Calcular quantidades", description: "Medir áreas com margem de perda" },
    { title: "Especificar rodapés", description: "Definir alturas e materiais" },
    { title: "Elaborar lista detalhada", description: "Criar planilha com metragens" },
  ],
  listas_loucas_metais: [
    { title: "Selecionar louças sanitárias", description: "Escolher vasos, cubas e bidês" },
    { title: "Selecionar metais sanitários", description: "Especificar torneiras e registros" },
    { title: "Definir acabamentos", description: "Escolher cromado, preto ou dourado" },
    { title: "Verificar compatibilidade", description: "Confirmar furação de cubas e bancadas" },
    { title: "Elaborar lista completa", description: "Quantificar por ambiente" },
  ],
  listas_luminarias: [
    { title: "Selecionar luminárias de teto", description: "Escolher pendentes e plafons" },
    { title: "Selecionar luminárias embutidas", description: "Especificar spots e painéis LED" },
    { title: "Selecionar arandelas", description: "Definir iluminação de parede" },
    { title: "Especificar lâmpadas", description: "Definir potências e temperaturas de cor" },
    { title: "Elaborar lista quantitativa", description: "Criar planilha de luminária por ambiente" },
  ],
  listas_tomadas_interruptores: [
    { title: "Definir linha de acabamento", description: "Escolher marca e modelo (Pial, Tramontina, etc)" },
    { title: "Selecionar cor e acabamento", description: "Definir branco, preto ou inox" },
    { title: "Quantificar tomadas", description: "Contar por tipo (2P+T, USB, etc)" },
    { title: "Quantificar interruptores", description: "Listar simples, paralelos e intermediários" },
    { title: "Elaborar lista completa", description: "Criar planilha de materiais elétricos" },
  ],
  listas_eletrodomesticos: [
    { title: "Listar eletrodomésticos de cozinha", description: "Fogão, forno, cooktop, coifa" },
    { title: "Listar eletrodomésticos de lavanderia", description: "Máquina de lavar e secar" },
    { title: "Especificar marcas e modelos", description: "Definir fabricantes preferidos" },
    { title: "Verificar medidas dos nichos", description: "Confirmar compatibilidade com projeto" },
    { title: "Elaborar lista de compras", description: "Criar planilha com especificações" },
  ],
  listas_pintura: [
    { title: "Definir cores por ambiente", description: "Escolher paleta cromática" },
    { title: "Selecionar tipos de tinta", description: "Acrílica, látex, esmalte, etc" },
    { title: "Especificar acabamentos", description: "Fosco, acetinado ou semi-brilho" },
    { title: "Calcular quantidades", description: "Medir áreas de aplicação" },
    { title: "Elaborar memorial de pintura", description: "Documentar especificações de cores" },
  ],
  listas_cortinas: [
    { title: "Medir vãos de janelas", description: "Conferir larguras e alturas" },
    { title: "Definir tipos de cortina", description: "Escolher entre persiana, rolô ou tecido" },
    { title: "Selecionar tecidos", description: "Definir materiais e cores" },
    { title: "Especificar sistemas", description: "Trilhos, varões ou suportes" },
    { title: "Elaborar lista de cortinas", description: "Quantificar por ambiente" },
  ],
  listas_papel_parede: [
    { title: "Selecionar estampas", description: "Escolher padrões por ambiente" },
    { title: "Definir tipo de papel", description: "Vinílico, TNT ou tecido" },
    { title: "Calcular metragem", description: "Medir áreas com rapport" },
    { title: "Especificar aplicação", description: "Definir parede inteira ou apenas faixa" },
    { title: "Elaborar lista de papéis", description: "Criar planilha com referências" },
  ],
  listas_box_espelhos: [
    { title: "Medir vãos de box", description: "Conferir dimensões dos banheiros" },
    { title: "Definir tipo de box", description: "Escolher entre articulado, pivotante ou de correr" },
    { title: "Selecionar vidros", description: "Especificar temperado ou laminado" },
    { title: "Definir acabamentos", description: "Escolher perfis cromados ou pretos" },
    { title: "Especificar espelhos", description: "Definir tamanhos e bisotês" },
    { title: "Elaborar lista completa", description: "Quantificar por banheiro" },
  ],
};

export function getTasksForSubcategory(subcategoryId: string): Array<{ title: string; description: string }> {
  return TASK_TEMPLATES[subcategoryId] || [
    { title: "Iniciar projeto", description: "Dar início ao desenvolvimento do projeto" },
    { title: "Desenvolver proposta", description: "Elaborar primeira versão do projeto" },
    { title: "Revisar projeto", description: "Verificar e ajustar detalhes técnicos" },
    { title: "Enviar para aprovação", description: "Submeter projeto para validação" },
    { title: "Finalizar projeto", description: "Concluir e arquivar documentação" },
  ];
}
